#! /bin/env dash

# Workspaces {{{
	bspc monitor -d 0 1 2 3 4 5 6 7 8 9
# }}}
# Gaps and padding {{{
	bspc config top_padding    12
	bspc config right_padding  12
	bspc config left_padding   12
	bspc config bottom_padding 12

	bspc config window_gap 9
# }}}
# Borders {{{
	bspc config border_width 1

	bspc config urgent_border_color          \#fa2772
   	bspc config focused_border_color         \#f1ebeb
	bspc config active_border_color          \#f1ebeb
	bspc config normal_border_color          \#272822
	bspc config presel_border_color          \#76715e

	bspc config focused_locked_border_color  \#66d9ee
	bspc config active_locked_border_color   \#66d9ee
	bspc config normal_locked_border_color   \#55bcce

	bspc config focused_sticky_border_color  \#e7db75
	bspc config active_sticky_border_color   \#e7db75
	bspc config normal_sticky_border_color   \#d4c96e

	bspc config focused_private_border_color \#66efd5
	bspc config active_private_border_color  \#66efd5
	bspc config normal_private_border_color  \#56b7a5
# }}}
# Other {{{
	bspc config split_ratio 0.53
	# bspc config status_prefix "stuff"
	# bspc config external_rules_command
	# bspc config initial_polarity
# }}}
# Boolean switches {{{
	bspc config history_aware_focus        true
	bspc config focus_by_distance          false
	bspc config borderless_monocle         true
	bspc config gapless_monocle            true
	bspc config focus_follows_pointer      true
	bspc config pointer_follows_focus      false
	bspc config pointer_follows_monitor    false
	bspc config auto_alternate             true
	bspc config auto_cancel                true
	# bspc config apply_floating_atom        true
	bspc config ignore_ewmh_focus          true
	bspc config center_pseudo_tiled        true
	bspc config remove_disabled_monitors   true
	bspc config remove_unplugged_monitors  true
	bspc config merge_overlapping_monitors false
# }}}

# vim: fdm=marker syntax=sh
